/* tslint:disable */
/* eslint-disable */
/**
 * Goallery
 * This is the API Specification for Goallery.
 *
 * The version of the OpenAPI document: 1.23.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ImageFeature
 */
export interface ImageFeature {
    /**
     * 
     * @type {string}
     * @memberof ImageFeature
     */
    pluginBlurryimage?: string;
}

/**
 * Check if a given object implements the ImageFeature interface.
 */
export function instanceOfImageFeature(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ImageFeatureFromJSON(json: any): ImageFeature {
    return ImageFeatureFromJSONTyped(json, false);
}

export function ImageFeatureFromJSONTyped(json: any, ignoreDiscriminator: boolean): ImageFeature {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'pluginBlurryimage': !exists(json, 'plugin.blurryimage') ? undefined : json['plugin.blurryimage'],
    };
}

export function ImageFeatureToJSON(value?: ImageFeature | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'plugin.blurryimage': value.pluginBlurryimage,
    };
}

